### ISSUE TITLE
getting error with multiple single-cell datasets (Integrated seurat object)

### ISSUE THREAD

**Issue by archana433** [kris-nader/scTherapy#2]
Hi
Very helpful tool 
 I am getting error when I am using Integrated seurat ( joint analysis of multiple single-cell datasets).

Error in Z[cell_markers_genes_score[jj, "gene_"], ] : 
  subscript out of bounds
In addition: Warning messages:
1: In checkGeneSymbols(markers_all) : x contains non-approved gene symbols
2: In checkGeneSymbols(markers_all) : x contains non-approved gene symbols
3: In sctype_score(scRNAseqData = seurat_object[["RNA"]]@scale.data,  :
  The dimension of input scRNAseqData matrix equals to 0, is it an empty matrix?

and when I checked my object 
a@assays$RNA@scale.data
<0 x 0 matrix>

Could it be possible to use this tool using Integrated multiple scRNA seurat object?

**Comment by kris-nader** [comment]
Hello @archana433 
Thank you for your comment. If the dimensions of your scaled integrated scRNAseq data is 0, I assume it is empty. 
Are you sure the integration is done correctly?  
If it is done correctly, you should be using the integrated data for example:  seurat4: `pbmc[["integrated"]]@scale.data`.  This could change depending on the version of seurat:  seurat5: `pbmc[["integrated"]]$scale.data` and should not be empty. 
We can continue to debug over email if this data is confidential. I would need a copy of the code you have been using to process the data and the seurat object(or a subset). please send to kristen.nader@helsinki.fi
best,
kristen
